#define DS18B2_Temperature_Probe 0x01
#define MKR_Environmental_Shield_Temperature 0x02
#define MKR_Environmental_Shield_Humidity 0x03
#define MKR_Environmental_Shield_Barometric_Pressure 0x04
#define MKR_Environmental_Shield_Illuminance 0x05
#define SparkFun_Weather_Meter_Wind_Speed 0x06
#define SparkFun_Weather_Meter_Wind_Direction 0x07
#define DFR_Weather_Meter_Rainfall 0x08
#define DFR_Conductivity_Meter 0x09
#define DFR_Ultrasonic_Distance 0x0A
#define PH 0x0B
#define Soil_Moisture_Sensor 0x0C
